import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

export default function Home() {
  const [people, setPeople] = useState([]);

  // Fetching the data
  useEffect(() => {
    const fetchData = async () => {
      // Fetch data
      const response = await fetch('/json/data.json');
      // Return json
      const json = await response.json();
      setPeople(json);
      }
      fetchData();
    }, []);
    

  // ****** MAP ****** //
const getAllItems = () => {
  return people.map((person) => (
    <p>{person.first_name} {person.last_name} {person.department} {person.age} {person.state}</p>
  ))
}



  // ***** REDUCE ***** //




  
  
  
  // ***** FILTER ***** //
  





  const Greeting = () => {
    return <div>
      <h1> Mock Data! </h1>
      <h2>Users</h2>
    </div>
  }
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Greeting/>
      <div>
        {getAllItems()}
      </div>
    </>
  )
}
